
# Erick Lu
# IHC_block_analyzer.R
# This script will read in the batch of output files generated by the matlab script and
# calculate "confinement" (how much to stain a and b mix?). 
# Designed to read in files with block size 25x25
# and generate data using threshold value 1-99%.
# The stains I was quantifying were: IgD (stain a) and GL7 (stain b)

#Read the batch files in:
########################################################################
batch_dir = "/Users/ericklu/Desktop/Bioinformatics/ihc_quant/pictures"
########################################################################
setwd(batch_dir)
batch_files = list.files(pattern = "_25x25.txt")
batch_files

#output: [1] "confined_25x25.txt" "disperse_25x25.txt"

#Set wd to data output location:
########################################################################
output_dir = "/Users/ericklu/Desktop/Bioinformatics/ihc_quant/output"
########################################################################
#dir.create(output_dir)

####################################################################################
# This script will return a confinement index using range 1-99
####################################################################################

#Initialize the arrays used to store the confinement statistics
confinement_index = array(1:length(batch_files))
ntop99 = array(1:length(batch_files))
nmid99 = array(1:length(batch_files))
nbottom99 = array(1:length(batch_files))
all_interval = c()
sr = array(1:length(batch_files))

#Initialize the array used to store the proportion table (for pooling graphs together)

#Loop through all the files in the folder
for (i in 1:length(batch_files)){
  
  # Read in the file name and assign data to a data.table object
  fileName = batch_files[i]
  setwd(batch_dir)
  
  # Define the names of each of the columns
  header_names = c('blocknum', 'length', 'width', 'IgD', 'GL7', 'proportion', 'IgD_max', 'GL7_max')
  data = read.table(fileName, sep = '\t')
  colnames(data) = header_names
  head(data)
  
  ####################################
  # Selection Criteria
  ####################################
  
  #1. Filter by correct block dimension: which (data$length == 25 & data$width == 25)
  filtered_data = data [ which(data$length == 25 & data$width == 25), ]
  
  #2. Omit blocks that have no IgD or GL7 stain.
  fdn = filtered_data [ which(filtered_data$proportion != 'NaN'), ]
  
  #3. filter out square on the edge of the follicle. Those that are low in IgD staining and
  #   also have less than 5% GL7 Stain.
  fdn_omit = fdn [ -which (fdn$IgD<75 & fdn$GL7<31.25, arr.ind=TRUE), ]
  
  #4. Sort the table based on proportion of IgD stain per block (high to low)
  sort.fdnpos = fdn_omit [ order(fdn_omit$proportion, decreasing = T), ]
  
  fdn_confinement = fdn_omit [ which (fdn_omit$GL7 > 31.25), ]
  #Calculate "confinement statistic" which is just the mean of the proportion
  confinement = mean(fdn_confinement$proportion)
  
  ############################################################
  #Extract data - # of points between the specified intervals
  ############################################################
  
  blocks_counted = length (which (fdn_omit$proportion <= 1))
  
  # 1-99
  numtop99 = length(which (fdn_omit$proportion <=1 & fdn_omit$proportion > 0.99))/blocks_counted # only IgD (stain_a)
  nummid99 = length(which (fdn_omit$proportion <= 0.99 & fdn_omit$proportion > 0.01))/blocks_counted # mixed IgD & GL7 (stain a and b)
  numbot99 = length(which (fdn_omit$proportion <= 0.01))/blocks_counted # only GL7 (stain_b)

  #Quality asssurance to make sure our fractions add up to 1.
  sum_ratio = numtop99 + nummid99 + numbot99
  
  #Draw the graph and export it to specified folder
  setwd(output_dir)
  png_name = gsub(".txt", "_Total.png", fileName)
  png(filename=png_name)
  plot (sort.fdnpos$proportion, main = fileName, xlab = "Sorted Block Index", ylab = "Proportion of IgD")
  abline (h=confinement, col = 'red')
  dev.off()
  
  #Store the confinement statistic in the pre-initialized array
  confinement_index[i]=confinement
  ntop99[i] = numtop99
  nmid99[i] = nummid99
  nbottom99[i] = numbot99
  
  sr[i] = sum_ratio
  
  # OPTIONAL: For each image pair, write the individual proportion file to the proportion directory. 
  # this can be used to graph single images or can be combined to create pooled datasets.
  # setwd(output_dir)
  # proportion_name = gsub (".txt", "_proportion.csv", fileName)
  # gl7.proportion = (1-sort.fdnpos$proportion)
  # write.csv (gl7.proportion, file = proportion_name)
  # 
  # blocks_counted = length (which (gl7.proportion <= 1))
  # abtop99 = length(which (gl7.proportion <=1 & gl7.proportion > 0.99))
  # abbot99 = blocks_counted - length(which (gl7.proportion <= 0.01))
  # 
  # intervals = c (fileName,numtop99, nummid99, numbot99, abtop99, abbot99, blocks_counted )
  # all_interval = cbind (all_interval, intervals)
}

#Print out the cutoff values so that the interval can be graphed in prism
#rownames(all_interval) = c("Genotype", "numtop99", "nummid99", "numbot99", "99 percent cutoff", "1 percent cutoff", "total blocks counted")
#write.csv(all_interval, file = "combined_proportions.csv")

#Bind the names of the files to the confinement values
cmatrix = cbind (batch_files, confinement_index, ntop99, nmid99, nbottom99, sr)
colnames (cmatrix) = c("file_name", "confinement", "only_stain_a", "mixed_stain", "only_stain_b","sum")

setwd(output_dir)
#Write the data out to a .csv file.
################################################################################
write.csv (cmatrix, file = "confinement_values_25x25.csv")
################################################################################




